### ISSUE TITLE
No registered env with id

### ISSUE THREAD

**Issue by COST-97** [rail-berkeley/d4rl#118]
Hello.
There are some issue.
`
Traceback (most recent call last):
  File "/home/amax/anaconda3/envs/pad/lib/python3.6/site-packages/gym/envs/registration.py", line 150, in spec
    return self.env_specs[id]
KeyError: 'halfcheetah-random-v0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "scripts/run_script.py", line 219, in <module>
    env = gym.make(args.env_name)
  File "/home/amax/anaconda3/envs/pad/lib/python3.6/site-packages/gym/envs/registration.py", line 184, in make
    return registry.make(id, **kwargs)
  File "/home/amax/anaconda3/envs/pad/lib/python3.6/site-packages/gym/envs/registration.py", line 105, in make
    spec = self.spec(path)
  File "/home/amax/anaconda3/envs/pad/lib/python3.6/site-packages/gym/envs/registration.py", line 167, in spec
    raise error.UnregisteredEnv("No registered env with id: {}".format(id))
gym.error.UnregisteredEnv: No registered env with id: halfcheetah-random-v0

`
Could you give me some advice?
Thank you.

**Comment by deepolicy** [comment]
What is the reason or solution?
