### ISSUE TITLE
I can't use maze environments

### ISSUE THREAD

**Issue by joseluperez1999** [rail-berkeley/d4rl#140]
Hi i'm trying to use maze2d-umaze-v1 dataset but i have the following error:

> Traceback (most recent call last):
  File "test.py", line 20, in <module>
    env = gym.make('maze2d-umaze-v1')
  File "C:\Users\user\miniconda3\envs\d3rlpyEnv2\lib\site-packages\gym\envs\registration.py", line 184, in make
    return registry.make(id, **kwargs)
  File "C:\Users\user\miniconda3\envs\d3rlpyEnv2\lib\site-packages\gym\envs\registration.py", line 106, in make
    env = spec.make(**kwargs)
  File "C:\Users\user\miniconda3\envs\d3rlpyEnv2\lib\site-packages\gym\envs\registration.py", line 76, in make
    env = cls(**_kwargs)
  File "C:\Users\user\miniconda3\envs\d3rlpyEnv2\lib\site-packages\d4rl\pointmaze\maze_model.py", line 175, in __init__
    mujoco_env.MujocoEnv.__init__(self, model_path=f.name, frame_skip=1)
  File "C:\Users\user\miniconda3\envs\d3rlpyEnv2\lib\site-packages\gym\envs\mujoco\mujoco_env.py", line 54, in __init__
    self.model = mujoco_py.load_model_from_path(fullpath)
  File "cymj.pyx", line 175, in mujoco_py.cymj.load_model_from_path
Exception: Failed to load XML file: C:\Users\user\AppData\Local\Temp\tmp6wt_ahnc.xml. mj_loadXML error: b'XML parse error at line 0, column 0:\nFailed to open file\n'

Solutions?

**Comment by Super1ce** [comment]
Same problem and i can't use antmaze too.Have any solve now?

**Comment by bear-power** [comment]
I have same problem too.Is there any solution?
