### ISSUE TITLE
Step-by-step instalation tutorial?

### ISSUE THREAD

**Issue by veax-void** [rail-berkeley/d4rl#156]
Hi, I assume that this project was made to help the RL community develop better algorithms for solving offline RL problems. I think that time should be spent exactly on model development and not on figuring out how to install and use provided env software.
So I assembled a little step-by-step guide on how to install D4RL. But I hope that maintainers can update wiki or readme file, thank you. (I can contribute this writeup with more explanations, just tell me where you want it)

[This is link to my attempt to set up everything](https://veax-void.github.io/voidlog.github.io/2022/05/27/d4rl_installation.html) 

PS: I am writing here, not because I wrote how to set everything up, but because I failed to do so.

**Comment by huangzizhen** [comment]
hi, when i test the code, I encountered the following bug.  Do u know how to solve it? thanks !!!
`Traceback (most recent call last):
  File "D:/PyProject/BCQ-master/text.py", line 5, in <module>
    env = gym.make('maze2d-umaze-v1')
  File "D:\Program Files\Anaconda3\envs\mujoco\lib\site-packages\gym\envs\registration.py", line 597, in make
    env = cls(**_kwargs)
  File "d:\d4rl\d4rl\pointmaze\maze_model.py", line 175, in __init__
    mujoco_env.MujocoEnv.__init__(self, model_path=f.name, frame_skip=1)
  File "D:\Program Files\Anaconda3\envs\mujoco\lib\site-packages\gym\envs\mujoco\mujoco_env.py", line 78, in __init__
    self.model = self._mujoco_bindings.MjModel.from_xml_path(fullpath)

ValueError: XML parse error 3:
Error=XML_ERROR_FILE_NOT_FOUND ErrorID=3 (0x3) Line number=0: filename=C:\Users\86137\AppData\Local\Temp\tmpfvbqdq7w.xml`

**Comment by agiachris** [comment]
I managed to fix this error @ivanvoid by modifying the gym version:
1. pip uninstall gym
2. pip install gym==0.23.1
