### ISSUE TITLE
Some dataset cannot be imported correctly.

### ISSUE THREAD

**Issue by sweetice** [rail-berkeley/d4rl#44]
When testing in gym, some dataset in d4rl seems to don't work.

```
res = ['ant_expert', 'ant_medium', 'ant_medium_expert', 'ant_mixed', 'ant_random', 'ant_random_expert',
       'halfcheetah_expert', 'halfcheetah_medium', 'halfcheetah_medium_expert', 'halfcheetah_mixed',
       'halfcheetah_random', 'hopper_expert', 'hopper_medium', 'hopper_medium_expert', 'hopper_mixed',
       'hopper_random', 'walker2d_expert', 'walker2d_medium', 'walker2d_medium_expert',
       'walker2d_random', 'walker_mixed'] 


res = [x.replace('_', '-') + '-v0' for x in res]

import d4rl
import gym
import mujoco_py

bad_case = []
good_case = []
for x in res:
    try:
        env = gym.make(x)
        good_case.append(x)
    except:
        bad_case.append(x)

print("Bad case", bad_case)
```

And the output:
```
Bad case ['ant-mixed-v0', 'ant-random-expert-v0', 'halfcheetah-mixed-v0', 'hopper-mixed-v0', 'walker-mixed-v0']
```

**Comment by justinjfu** [comment]
We renamed the "mixed" environments to "medium-replay" as a more descriptive name (they are training replay buffers taken from the medium agent).

ant-random-expert-v0 is not throwing an error for me - could you post what error you are getting?

**Comment by sweetice** [comment]
Thank you Justin! Following your suggestion, I can import "medium-replay" env correctly. 
```
>>> env = gym.make("ant-medium-replay-v0")
/home/mirror/anaconda3/lib/python3.7/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))
```
However, there is still a problem when importing 'ant-random-expert-v0' environment.
Here is the error raised by making 'ant-random-expert-v0' environment.

```
Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import free_mjc
>>> import mujoco_py
>>> import gym
>>> import d4rl
Warning: Flow failed to import. Set the environment variable D4RL_SUPPRESS_IMPORT_ERROR=1 to suppress this message.
No module named 'flow'
Warning: CARLA failed to import. Set the environment variable D4RL_SUPPRESS_IMPORT_ERROR=1 to suppress this message.
No module named 'carla'
>>> env = gym.make("ant-random-expert-v0")
Traceback (most recent call last):
  File "/home/mirror/anaconda3/lib/python3.7/site-packages/gym/envs/registration.py", line 121, in spec
    return self.env_specs[id]
KeyError: 'ant-random-expert-v0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mirror/anaconda3/lib/python3.7/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/home/mirror/anaconda3/lib/python3.7/site-packages/gym/envs/registration.py", line 89, in make
    spec = self.spec(path)
  File "/home/mirror/anaconda3/lib/python3.7/site-packages/gym/envs/registration.py", line 131, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: ant-random-expert-v0
```

**Comment by justinjfu** [comment]
Could you make sure you are running an up-to-date version, and that 'ant-random-expert-v0' is registered at this line? https://github.com/rail-berkeley/d4rl/blob/master/d4rl/gym_mujoco/__init__.py#L237
