### ISSUE TITLE
KeyError: 'mini-kitchen-microwave-kettle-light-slider-v0'

### ISSUE THREAD

**Issue by csufangyu** [rail-berkeley/d4rl#58]
hi I want to test the case in kitchen,but I get a error,can you help me?thanks very much!
```
Python 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:25:08) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gym
>>> import d4rl
Warning: Flow failed to import. Set the environment variable D4RL_SUPPRESS_IMPORT_ERROR=1 to suppress this message.
No module named 'flow'
/home/fangyu/.conda/envs/d4rl/lib/python3.7/site-packages/glfw/__init__.py:834: GLFWError: (65544) b'X11: The DISPLAY environment variable is missing'
  warnings.warn(message, GLFWError)
Warning: CARLA failed to import. Set the environment variable D4RL_SUPPRESS_IMPORT_ERROR=1 to suppress this message.
No module named 'carla'
>>> env = gym.make('mini-kitchen-microwave-kettle-light-slider-v0')
Traceback (most recent call last):
  File "/home/fangyu/.conda/envs/d4rl/lib/python3.7/site-packages/gym/envs/registration.py", line 121, in spec
    return self.env_specs[id]
KeyError: 'mini-kitchen-microwave-kettle-light-slider-v0'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/fangyu/.conda/envs/d4rl/lib/python3.7/site-packages/gym/envs/registration.py", line 145, in make
    return registry.make(id, **kwargs)
  File "/home/fangyu/.conda/envs/d4rl/lib/python3.7/site-packages/gym/envs/registration.py", line 89, in make
    spec = self.spec(path)
  File "/home/fangyu/.conda/envs/d4rl/lib/python3.7/site-packages/gym/envs/registration.py", line 131, in spec
    raise error.UnregisteredEnv('No registered env with id: {}'.format(id))
gym.error.UnregisteredEnv: No registered env with id: mini-kitchen-microwave-kettle-light-slider-v0
```

**Comment by justinjfu** [comment]
Hi, you should try the environment 'kitchen-complete-v0', which uses the mini dataset.
